Vagrant.configure("2") do |config|

  # cluster default gateway ip
  gateway_ip = "192.168.250.1"

  # shell provisioning
  del_default_gateway = "route del default gw 0"
  add_gateway_command = "route add default gw #{ gateway_ip }"

  # node configuration
  ndata = {
    name: "moriarty",
    disk: "50G",
    ip: "192.168.250.50",
    memory: "1024"
  }

  config.vm.box = "ubuntu/xenial64"
  config.disksize.size = ndata[:disk]
  config.vm.hostname = ndata[:name]
  config.vm.network "public_network", ip: ndata[:ip]

  config.vm.provision "shell", inline: del_default_gateway
  config.vm.provision "shell", inline: add_gateway_command

  config.vm.provider "virtualbox" do |vb|
    vb.memory = ndata[:memory]
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "ansible/playbook.yml"
  end
end
