- name: Remove swapfile from /etc/fstab
  mount:
    path: "{{ item }}"
    fstype: swap
    state: absent
  with_items:
    - none
    - swap

- name: Disable swap
  command: swapoff -a
  when: ansible_swaptotal_mb > 0

- name: networking requirements
  command: "{{ item }}"
  with_items:
    - sudo modprobe br_netfilter
    - sudo sysctl net.bridge.bridge-nf-call-iptables=1

- name: base libraries
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - curl
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg2
    - software-properties-common
    - ebtables
    - ethtool
    - bridge-utils

- name: add keys
  apt_key:
    url: "{{ item }}"
  with_items:
    - https://download.docker.com/linux/ubuntu/gpg
    - https://packages.cloud.google.com/apt/doc/apt-key.gpg

- name: add repositories
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items:
    - deb https://download.docker.com/linux/ubuntu xenial stable
    - deb http://apt.kubernetes.io/ kubernetes-xenial main

- name: install docker and k8s
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - docker-ce=17.03.2~ce-0~ubuntu-xenial
    - docker-compose
    - kubelet
    - kubeadm
    - kubectl

- name: adding kubi to docker group
  user:
    name: kubi
    groups:
      - docker
    append: yes
