Vagrant.configure("2") do |config|
  config.vm.box = "debian/stretch64"
  config.vm.box_version = "9.4.0"

  config.vm.hostname = "mycroft"
  config.vm.network "public_network", ip: "192.168.250.104"

  config.vm.provider "virtualbox" do |vb|
     vb.memory = "2048"
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "../../provisioning/playbook.yml"
  end
end
