- name: create shared directories
  file:
    path: "/var/nfs"
    state: directory
    owner: nobody
    group: nogroup
    mode: u=rw,g=rw,o=rw
  creates: /var/nfs
  when: nfs_active == "yes"

- name: copy /etc/exports
  template:
    src: exports.j2
    dest: /etc/exports
    owner: root
    group: root
  creates: /etc/exports
  when: nfs_active == "yes"

- name: restart nfs server
  service:
    name: nfs-kernel-server
    state: restarted
  when: nfs_active == "yes"
