Vagrant.configure("2") do |config|
  config.vm.box = "debian/stretch64"
  config.vm.box_version = "9.4.0"

  # this requires: vagrant plugin install vagrant-disksize
  config.disksize.size = '10GB'

  config.vm.hostname = "mycroft"
  config.vm.network "private_network", ip: "172.17.8.103"
  config.vm.network "public_network", bridge: "enp0s25: eth0", auto_config: false
  config.vm.provision "shell",
                      run: "always",
                      inline: "route add default gw 192.168.250.1"

  config.vm.provider "virtualbox" do |vb|
     vb.memory = "2048"
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "../../provisioning/playbook.yml"
  end
end
