Vagrant.configure("2") do |config|
  config.vm.box = "debian/stretch64"
  config.vm.box_version = "9.4.0"

  # this requires: vagrant plugin install vagrant-disksize
  config.disksize.size = '10GB'

  config.vm.hostname = "sherlock"
  config.vm.network "public_network", ip: "192.168.250.102"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "../../provisioning/playbook.yml"
  end
end
